# Generated by Django 3.1 on 2020-09-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_carousel_heading', models.CharField(max_length=100)),
                ('top_carousel_paragraph', models.CharField(max_length=500)),
                ('upper_content_heading', models.CharField(max_length=500)),
                ('upper_content', models.CharField(max_length=500)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('profile_heading', models.CharField(max_length=50)),
                ('profile_intro', models.CharField(max_length=100)),
                ('gallary_image', models.ImageField(upload_to='')),
                ('lower_content_heading', models.CharField(max_length=500)),
                ('lower_content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
