# Generated by Django 3.1 on 2020-09-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallary_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='gallary_image',
        ),
    ]
