# Generated by Django 3.1 on 2020-09-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200902_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_para', models.CharField(max_length=9000)),
                ('second_para', models.CharField(max_length=9000)),
                ('third_para', models.CharField(max_length=9000)),
            ],
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='lower_content',
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='upper_content',
        ),
    ]
