# Generated by Django 3.1 on 2020-09-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200902_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallary',
            old_name='gallary_image',
            new_name='gallary_image1',
        ),
        migrations.AddField(
            model_name='gallary',
            name='gallary_image2',
            field=models.ImageField(blank=True, upload_to='gallary_image'),
        ),
        migrations.AddField(
            model_name='gallary',
            name='gallary_image3',
            field=models.ImageField(blank=True, upload_to='gallary_image'),
        ),
        migrations.AddField(
            model_name='gallary',
            name='gallary_image4',
            field=models.ImageField(blank=True, upload_to='gallary_image'),
        ),
        migrations.AddField(
            model_name='gallary',
            name='gallary_image5',
            field=models.ImageField(blank=True, upload_to='gallary_image'),
        ),
        migrations.AddField(
            model_name='gallary',
            name='gallary_image6',
            field=models.ImageField(blank=True, upload_to='gallary_image'),
        ),
        migrations.AddField(
            model_name='gallary',
            name='gallary_image7',
            field=models.ImageField(blank=True, upload_to='gallary_image'),
        ),
        migrations.AddField(
            model_name='gallary',
            name='gallary_image8',
            field=models.ImageField(blank=True, upload_to='gallary_image'),
        ),
    ]
