# Generated by Django 3.1 on 2020-09-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200903_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallary',
            old_name='gallary_image1',
            new_name='gallary_image',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='gallary_image2',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='gallary_image3',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='gallary_image4',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='gallary_image5',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='gallary_image6',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='gallary_image7',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='gallary_image8',
        ),
    ]
