# Generated by Django 3.1 on 2020-09-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200903_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_picture'),
        ),
    ]
